algo = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(algo))
print('Só tem espaços? ', algo.isspace())
print('Só tem número? ', algo.isnumeric())
print('Só tem letras? ', algo.isalpha())
print('Só tem letras ou número? ', algo.isalnum())
print('Só tem números decimais? ', algo.isdecimal())
print('Só tem letras minúsculas? ', algo.islower())
print('Só tem letras maiúsculas? ', algo.isupper())
print('Só tem caracteres em geral? ', algo.isascii())
print('Está capitalizada', algo.istitle())
